# Generated by Django 5.0 on 2024-01-02 01:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_remove_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='definition',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
